### PR TITLE
Add rubocop

### PR DESCRIPTION
**Pull request by NikitaNaumenko**
Good evening, I added a rubocop file and called Travis #5 . I really want to help you and the community in working on the events of the khans, and get most expirience. Thanks

### CODE REVIEW

**Comment by davydovanton** [comment]
hey, thanks for this changes! I'm a little busy now but I'll review PR ASAP. Thanks again 👍

**Comment by davydovanton** [comment]
hey, sorry for the long response. I added our base rubocop config and fix style issues in the project. Could you rebase your PR and drop your rules from rubocop config file?

**Comment by NikitaNaumenko** [comment]
Hello! Thanks for answer, yes, no problem, i'm going to do it)

**Comment by NikitaNaumenko** [comment]
I updated PR, but when i did it latest rubocop version was 0.50, maybe me need to updated it for current version?

**Comment by davydovanton** [comment]
hey, let's do it in next PR :)

**Comment by davydovanton** [comment]
Thanks for helping! 👏

**Pull request merged**
